export const GET_ALL_EVENT_CLOSURE = "GET_ALL_EVENT_CLOSURE";
export const CREATE_EVENT_CLOSURE = "CREATE_EVENT_CLOSURE";
export const UPDATE_EVENT_CLOSURE = "UPDATE_EVENT_CLOSURE";
export const DELETE_EVENT_CLOSURE = "EVENT_CLOSURE_DELETE";
export const ADD_TO_EVENT_CLOSURE = "ADD_TO_EVENT_CLOSURE";
export const ACTIVE_EVENT_CLOSURE = "ACTIVE_EVENT_CLOSURE";

export const API = "API";
export const SET_PROJECT = "SET_PROJECT";