export const GET_ALL_EVENT_PLANNER = "GET_ALL_EVENT_PLANNER";
export const CREATE_EVENT_PLANNER = "CREATE_EVENT_PLANNER";
export const UPDATE_EVENT_PLANNER = "UPDATE_EVENT_PLANNER";
export const DELETE_EVENT_PLANNER = "EVENT_PLANNER_DELETE";
export const ADD_TO_EVENT_PLANNER = "ADD_TO_EVENT_PLANNER";
export const ACTIVE_EVENT_PLANNER = "ACTIVE_EVENT_PLANNER";


export const API = "API";
export const SET_PROJECT = "SET_PROJECT";